server:
  port: 8083

spring:

  application:
    name: keycloak-embedded

  jpa:
    defer-datasource-initialization: true

keycloak:
  server:
    contextPath: /auth
    username: keycloak_usr
    password: keycloak_pwd
